[package]
name = "monstorr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monstorr-lib = { path = "../monstorr-lib" }
clap = { version="3.1.2", features=["derive"] }

